CREATE TABLE ITEM(
	ITEM_ID INT PRIMARY KEY,
	REGION_NAME VARCHAR,
	COUNTRY_NAME VARCHAR,
	ITEM_TYPE VARCHAR,
	UNITS_SOLD INT
	)
Select *from ITEM

INSERT INTO ITEM(ITEM_ID,REGION_NAME,COUNTRY_NAME,ITEM_TYPE,UNITS_SOLD)
VALUES(101,'MIDDLE EAST','LIBYA','COSMETICS',8446),
      (202,'NORTH AMERICA','CANADA','VEGETABLES',3018),
      (303,'ASIA','JAPAN','CEREAL',3322)
Select *from ITEM
DELETE  FROM ITEM WHERE ITEM_ID =1 
Select *from ITEM

INSERT INTO ITEM(ITEM_ID,REGION_NAME,COUNTRY_NAME,ITEM_TYPE,UNITS_SOLD)
VALUES(104,'EUROPE','ARMENIA','COSMETICS',1517),
      (205,'NORTH AMERICA','CANADA','VEGETABLES',3019),
      (306,'ASIA','JAPAN','CEREAL',3323)
Select *from ITEM


COPY item (item_id, region_name, country_name, item_type, units_sold)
FROM 'D:\sql task 4\1000 record set.csv'
DELIMITER ','
CSV HEADER;

Select *from ITEM
COPY ITEM from 'D:\item_28th-july_2024_data.csv'DELIMITER ','CSV HEADER;

Select * from ITEM


















        